pod:
  port: 5001
  image: notilya4/db-tests.spammer:latest
  
  nodeSelector:
    node-role.kubernetes.io/worker: "true"

sql_server:
  host: sql-server.sql-server,1433

postgres:
  host: postgres.postgres

nginx:
  address: http://nginx.nginx

kafka:
  bootstrap_servers: kafka-kafka-bootstrap.strimzi:9092

s3:
  access_key:
  secret_key:

default_loglevel: Warning