- name: Install packages
  hosts: all
  become: true
  tasks:
    - name: Install microk8s
      register: microk8s
      snap:
        name: microk8s
        state: present
        classic: true
      when: true

    - name: Enable hostpath-storage addon in microk8s
      command: microk8s enable hostpath-storage
      when: microk8s is not skipped