outputPath := "../.output"

apply path:
    terraform -chdir="./{{path}}" init -upgrade
    terraform -chdir="./{{path}}" apply -auto-approve

destroy path:
    terraform -chdir="./{{path}}" init -upgrade
    terraform -chdir="./{{path}}" destroy -auto-approve

ssh path:
    ssh -o StrictHostKeychecking=no ubuntu@$(cat {{outputPath}}/{{path}}/nat_ip_address.txt) -i {{outputPath}}/{{path}}/ssh.key