apply path:
    terraform -chdir="./{{path}}" init -upgrade
    terraform -chdir="./{{path}}" apply -auto-approve

destroy path:
    terraform -chdir="./{{path}}" init -upgrade
    terraform -chdir="./{{path}}" destroy -auto-approve

ssh path:
    ssh -o StrictHostKeychecking=no ubuntu@$(cat ./{{path}}/.output/nat_ip_address.txt) -i ./{{path}}/.output/ssh.key