apply:
    terraform init -upgrade
    terraform apply -var-file="terraform.tfvars" -auto-approve

destroy:
    terraform init -upgrade
    terraform destroy -auto-approve

ssh:
    ssh -o StrictHostKeychecking=no ubuntu@$(cat ./output/nat_ip_address.txt) -i ./output/ssh.key