{
 "title": "Spammer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(runner_execution_duration_us_count,pod)"
    }
   },
   {
    "name": "test_name",
    "label": "test_name",
    "query": {
     "query": "label_values(runner_execution_duration_us_count,test_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Avg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (pod, test_name) ((idelta(runner_execution_duration_us_sum{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]) / idelta(runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval])))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (pod, test_name) (irate (runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "999 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (pod, test_name) (histogram_quantile(0.999, idelta(runner_execution_duration_us_bucket{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval])))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Sum Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, test_name) (irate (runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  { "title": "Per runner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(idelta(runner_execution_duration_us_sum{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]) / idelta(runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]))",
     "legendFormat": "{{runner_index}} - {{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate (runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval])",
     "legendFormat": "{{runner_index}} - {{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "999 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, idelta(runner_execution_duration_us_bucket{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]))",
     "legendFormat": "{{runner_index}} - {{test_name}} - {{pod}}"
    }
   ]
  }
 ]
}