{
 "title": "Spammer mod",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(runner_execution_duration_us_count,pod)"
    }
   },
   {
    "name": "test_name",
    "label": "test_name",
    "query": {
     "query": "label_values(runner_execution_duration_us_count,test_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Avg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (pod, test_name) ((idelta(runner_execution_duration_us_sum{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]) / idelta(runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval])))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Inner latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (pod, test_name) ((idelta(batching_internal_duration_ms_sum{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]) / idelta(batching_internal_duration_ms_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval])))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Strategy sleep",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (pod, test_name) ((idelta(batching_strategy_sleep_duration_ms_sum{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]) / idelta(batching_strategy_sleep_duration_ms_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval])))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Wait",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (pod, test_name) ((idelta(batching_wait_duration_ms_sum{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]) / idelta(batching_wait_duration_ms_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval])))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Queue length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "system_runtime_threadpool_queue_length",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (pod, test_name) (irate (runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Work items per sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "irate(system_runtime_threadpool_completed_items_count_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sum Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, test_name) (irate (runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]))",
     "legendFormat": "{{test_name}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "system_runtime_threadpool_thread_count",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Per runner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "(idelta(runner_execution_duration_us_sum{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]) / idelta(runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]))",
       "legendFormat": "{{runner_index}} - {{test_name}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate (runner_execution_duration_us_count{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval])",
       "legendFormat": "{{runner_index}} - {{test_name}} - {{pod}}"
      }
     ]
    },
    {
     "title": "999 quantile",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.999, idelta(runner_execution_duration_us_bucket{pod=~\"$pod\", test_name=~\"$test_name\"}[$__rate_interval]))",
       "legendFormat": "{{runner_index}} - {{test_name}} - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}