apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        date: {{ now | quote }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
          - name: ASPNETCORE_URLS
            value: http://*:5000
          - name: SqlServerConn__Server
            value: {{ .Values.sql_server.host }}
          - name: SqlServerConn__Database
            value: {{ .Values.sql_server.database }}
          - name: PostgresConn__Host
            value: {{ .Values.postgres.host }}
          - name: PostgresConn__Port
            value: {{ .Values.postgres.port | quote }}
          - name: SqlServerForwardSpammer__ParallelExecutions
            value: {{ .Values.myapp.parallel_executions | quote }}
          - name: SqlServerForwardSpammer__RetriesCount
            value: {{ .Values.myapp.retries_count | quote }}
          - name: TestName
            value: {{ .Values.testName }}
          - name: NginxAddress
            value: {{ .Values.nginx_address }}
          - name: Logging__LogLevel__Default
            value: {{ .Values.default_loglevel }}
          - name: DOTNET_DiagnosticPorts
            value: /diag/dotnet-monitor.sock
          - name: DOTNET_ThreadPool_ThreadsToKeepAlive
            value: '300'
          ports:
          - containerPort: 5000
          volumeMounts:
          - mountPath: /diag
            name: diagvol
          resources:
            requests:
              cpu: {{ .Values.cpu }}
              memory: {{ .Values.memory }}
        - name: dotnet-monitor
          args:
          - collect
          - --no-auth
          image: mcr.microsoft.com/dotnet/monitor:8
          env:
          - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
            value: Listen
          - name: DOTNETMONITOR_Storage__DefaultSharedPath
            value: /diag
          - name: DOTNETMONITOR_Urls
            value: http://*:52323
          ports:
          - containerPort: 52323
          volumeMounts:
          - mountPath: /diag
            name: diagvol
      volumes:
      - name: diagvol
        emptyDir: {}