apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        date: {{ now | quote }}
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.pod.image }}
          imagePullPolicy: Always
          env:
          - name: ASPNETCORE_URLS
            value: http://*:5000
          - name: SqlServerConn__Server
            value: {{ .Values.sql_server.host }}
          - name: PostgresConn__Host
            value: {{ .Values.postgres.host }}
          - name: NginxAddress
            value: {{ .Values.nginx.address }}
          - name: Logging__LogLevel__Default
            value: {{ .Values.default_loglevel }}
          - name: DOTNET_DiagnosticPorts
            value: /diag/dotnet-monitor.sock
          ports:
          - containerPort: 5000
          volumeMounts:
          - mountPath: /diag
            name: diagvol
          {{- with .Values.pod.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: dotnet-monitor
          args:
          - collect
          - --no-auth
          image: mcr.microsoft.com/dotnet/monitor:8
          env:
          - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
            value: Listen
          - name: DOTNETMONITOR_Storage__DefaultSharedPath
            value: /diag
          - name: DOTNETMONITOR_Urls
            value: http://*:52323
          ports:
          - containerPort: 52323
          volumeMounts:
          - mountPath: /diag
            name: diagvol
      volumes:
      - name: diagvol
        emptyDir: {}