apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        date: {{ now | quote }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: http://*:5000
            - name: SqlServerConn__Server
              value: {{ .Values.sql_server.host }}
            - name: SqlServerConn__Database
              value: {{ .Values.sql_server.database }}
            - name: SqlServerForwardSpammer__ParallelExecutions
              value: {{ .Values.myapp.parallel_executions | quote }}
            - name: SqlServerForwardSpammer__RetriesCount
              value: {{ .Values.myapp.retries_count | quote }}
            - name: TestName
              value: {{ .Values.testName }}
            - name: NginxAddress
              value: {{ .Values.nginx_address }}
            - name: Logging__LogLevel__Default
              value: {{ .Values.default_loglevel }}
          ports:
            - containerPort: 5000
          {{- if .Values.resourcesEnabled }}
          resources:
            limits:
              cpu: {{ .Values.cpu }}
              memory: {{ .Values.memory }}
          {{- end }}