apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-port
  labels:
    app: {{ .Release.Name }}-node-port
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: myapp
      port: 5000
      nodePort: 31076
      targetPort: 5000