apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: myapp
      port: {{ .Values.pod.port }}
      targetPort: 5000
    - name: metrics
      port: 8889
      targetPort: 8889
    - name: dotnet-monitor
      port: 52323
      targetPort: 52323