apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: 1433
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-0