installCRDs: true
nodeSelector:
  node-role.kubernetes.io/worker: "true"

webhook:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"

cainjector:
  nodeSelector:
    node-role.kubernetes.io/worker: "true"