compactor:
  nodeSelector:
    node.kubernetes.io/role: worker
gateway:
  nodeSelector:
    node.kubernetes.io/role: worker
distributor:
  nodeSelector:
    node.kubernetes.io/role: worker
ingester:
  nodeSelector:
    node.kubernetes.io/role: worker
querier:
  nodeSelector:
    node.kubernetes.io/role: worker
queryFrontend:
  nodeSelector:
    node.kubernetes.io/role: worker
queryScheduler:
  nodeSelector:
    node.kubernetes.io/role: worker
global:
  security:
    allowInsecureImages: true
loki:
  image:
    repository: bitnamilegacy/grafana-loki
gateway:
  image:
    repository: bitnamilegacy/nginx
volumePermissions:
  image:
    repository: bitnamilegacy/os-shell
grafanaalloy:
  image:
    repository: bitnamilegacy/grafana-alloy
  alloy:
    image:
      repository: bitnamilegacy/grafana-alloy
  configReloader:
    image:
      repository: bitnamilegacy/configmap-reload
memcachedchunks:
  image:
    repository: bitnamilegacy/memcached
memcachedfrontend:
  image:
    repository: bitnamilegacy/memcached
metrics:
  enabled: true
  serviceMonitor:
    enabled: true