fullnameOverride: postgres

primary:
  service:
    type: LoadBalancer
    ports:
      postgresql: 5432
  extendedConfiguration: |
    track_io_timing = on
    track_wal_io_timing = on
    track_functions = all
    wal_sync_method = fdatasync
    shared_preload_libraries = 'pg_stat_statements'
    shared_buffers = 524288
    max_wal_size = 10GB
    checkpoint_timeout = 300
    max_connections = 999
  resources:
    requests:
      cpu: '2'
      memory: 2Gi
  persistence:
    size: 100Gi
  containerSecurityContext:
    allowPrivilegeEscalation: true
    privileged: true
    runAsNonRoot: false

auth:
  postgresPassword: pgpass
  database: test1

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
