fullnameOverride: postgres

primary:
  service:
    type: LoadBalancer
    ports:
      postgresql: 5432

resources:
  requests:
    cpu: '2'
    memory: 2Gi

persistence:
  size: 50Gi

auth:
  postgresPassword: pgpass