repositories:
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts
- name: traefik
  url: https://traefik.github.io/charts
- name: jetstack
  url: https://charts.jetstack.io
- name: cilium
  url: https://helm.cilium.io/

releases:
- name: cilium
  namespace: cilium
  chart: cilium/cilium
  disableValidationOnInstall: true

- name: traefik
  namespace: traefik
  chart: traefik/traefik
  disableValidationOnInstall: true
  needs:
  - cilium/cilium
  values:
  - ./values/traefik.yaml

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  disableValidationOnInstall: true
  needs:
  - cilium/cilium
  values:
  - ./values/cert-manager.yaml

- name: loki
  namespace: loki
  chart: bitnami/grafana-loki
  needs:
  - cilium/cilium
  values:
  - compactor:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    gateway:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    distributor:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    ingester:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    querier:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    queryFrontend:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    queryScheduler:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"

- name: monitoring
  namespace: monitoring
  chart: prometheus/kube-prometheus-stack
  disableValidationOnInstall: true
  needs:
  - cilium/cilium
  - traefik/traefik
  - loki/loki
  values:
  - ./values/monitoring.yaml.gotmpl

- name: nginx
  namespace: nginx
  chart: bitnami/nginx
  installed: true
  needs:
  - cilium/cilium
  - traefik/traefik
  values:
  - ./values/nginx.yaml.gotmpl

- name: myapp
  namespace: myapp
  chart: ./charts/myapp
  disableValidationOnInstall: true
  needs:
  - cilium/cilium
  - traefik/traefik