repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    disableValidationOnInstall: true
    values:
    - service:
        type: NodePort
      ports:
        web:
          nodePort: 32160
        websecure:
          nodePort: 30643
  
  - name: nginx
    namespace: nginx
    chart: bitnami/nginx
    installed: true
    values:
    - service:
        type: ClusterIP
        ports:
          http: 3001
      readinessProbe:
        enabled: false
      livenessProbe:
        enabled: false
      resourcesPreset: none
      tls:
        enabled: false
  
  - name: nginx-ingress
    chart: ./traefik-routes
    disableValidationOnInstall: true
    needs:
    - traefik/traefik
    - nginx/nginx
    installed: true