bases:
- ./helmfile.base.yaml

repositories:
- name: kafka-ui
  url: https://provectus.github.io/kafka-ui-charts

releases:
- name: myapp1
  namespace: myapp1
  chart: ./charts/myapp
  disableValidationOnInstall: true
  installed: false
  needs:
  - cilium/cilium
  - traefik/traefik

- name: myapp2
  namespace: myapp2
  chart: ./charts/myapp
  disableValidationOnInstall: true
  installed: false
  needs:
  - cilium/cilium
  - traefik/traefik

- name: myapp3
  namespace: myapp3
  chart: ./charts/myapp
  disableValidationOnInstall: true
  installed: false
  needs:
  - cilium/cilium
  - traefik/traefik

- name: strimzi-operator
  namespace: strimzi
  chart: oci://quay.io/strimzi-helm/strimzi-kafka-operator
  disableValidationOnInstall: true
  version: ~0.42.0
  needs:
  - cilium/cilium

- name: kafka
  namespace: strimzi
  chart: ./charts/strimzi-kafka
  disableValidationOnInstall: true
  needs:
  - cilium/cilium
  - strimzi/strimzi-operator

- name: kafka-ui
  namespace: kafka-ui
  chart: kafka-ui/kafka-ui
  needs:
  - cilium/cilium
  - traefik/traefik
  values:
  - yamlApplicationConfig:
      kafka:
        clusters:
          - name: kafka1
            bootstrapServers:  kafka.kafka:9092
      auth:
        type: disabled
      management:
        health:
          ldap:
            enabled: false
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      host: kafka-ui.krupcov.ru
      ingressClassName: traefik
    env:
      - name: DYNAMIC_CONFIG_ENABLED
        value: 'true'
    nodeSelector:
      node-role.kubernetes.io/worker: "true"