bases:
- ./helmfile.base.yaml

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: kafka-ui
  url: https://provectus.github.io/kafka-ui-charts

releases:
- name: kafka
  namespace: kafka
  chart: bitnami/kafka
  values:
  - kraft:
      clusterId: jh08hbDufMo4Pr454I4zL1
    provisioning:
      nodeSelector:
        node-role.kubernetes.io/kafka: "true"
    controller:
      resourcesPreset: none
    broker:
      resourcesPreset: none
    listeners:
      client:
        protocol: PLAINTEXT
      controller:
        protocol: PLAINTEXT
      interbroker:
        protocol: PLAINTEXT
      external:
        protocol: PLAINTEXT
    extraConfig:
      #replica.lag.time.max.ms: 500
      min.insync.replicas: 2

- name: kafka-ui
  namespace: kafka-ui
  chart: kafka-ui/kafka-ui
  values:
  - yamlApplicationConfig:
      kafka:
        clusters:
          - name: kafka1
            bootstrapServers:  kafka.kafka:9092
      auth:
        type: disabled
      management:
        health:
          ldap:
            enabled: false
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      host: kafka-ui.krupcov.ru
    env:
      - name: DYNAMIC_CONFIG_ENABLED
        value: 'true'