repositories:
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts
- name: traefik
  url: https://traefik.github.io/charts
- name: open-telemetry
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
- name: jetstack
  url: https://charts.jetstack.io
- name: cilium
  url: https://helm.cilium.io/

releases:
- name: cilium
  namespace: cilium
  chart: cilium/cilium
  disableValidationOnInstall: true

- name: traefik
  namespace: traefik
  chart: traefik/traefik
  disableValidationOnInstall: true
  needs:
  - cilium/cilium
  values:
  - ./values/traefik.yaml

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  disableValidationOnInstall: true
  needs:
  - cilium/cilium
  values:
  - ./values/cert-manager.yaml

- name: open-telemetry
  namespace: open-telemetry
  chart: open-telemetry/opentelemetry-operator
  disableValidationOnInstall: true
  needs:
  - cert-manager/cert-manager
  - cilium/cilium
  values:
  - ./values/open-telemetry.yaml

- name: monitoring
  namespace: monitoring
  chart: prometheus/kube-prometheus-stack
  disableValidationOnInstall: true
  needs:
  - cilium/cilium
  values:
  - ./values/monitoring.yaml.gotmpl

- name: nginx
  namespace: nginx
  chart: bitnami/nginx
  installed: true
  needs:
  - cilium/cilium
  values:
  - ./values/nginx.yaml.gotmpl

- name: myapp
  namespace: myapp
  chart: ./myapp
  disableValidationOnInstall: true
  needs:
  - open-telemetry/open-telemetry