repositories:
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts
- name: traefik
  url: https://traefik.github.io/charts
- name: open-telemetry
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: traefik
  namespace: traefik
  chart: traefik/traefik
  disableValidationOnInstall: true
  values:
  - ./values/traefik.yaml

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  disableValidationOnInstall: true
  values:
  - ./values/cert-manager.yaml

- name: open-telemetry
  namespace: open-telemetry
  chart: open-telemetry/opentelemetry-operator
  disableValidationOnInstall: true
  needs:
  - cert-manager/cert-manager
  values:
  - ./values/open-telemetry.yaml

- name: monitoring
  namespace: monitoring
  chart: prometheus/kube-prometheus-stack
  disableValidationOnInstall: true
  values:
  - ./values/monitoring.yaml.gotmpl