repositories:
- name: prometheus
  url: https://prometheus-community.github.io/helm-charts
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: loki
  namespace: loki
  chart: bitnami/grafana-loki
  values:
  - ./values/loki.yaml

- name: monitoring
  namespace: monitoring
  chart: prometheus/kube-prometheus-stack
  disableValidationOnInstall: true
  version: "60.5.0"
  values:
  - ./values/monitoring.yaml.gotmpl

- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: "4.11.2"
  values:
  - ./values/ingress-nginx.yaml

- name: nginx
  namespace: nginx
  chart: bitnami/nginx
  version: "18.1.7"
  values:
  - ./values/nginx.yaml.gotmpl

- name: myapp
  namespace: myapp
  chart: ./charts/myapp
  disableValidationOnInstall: true