{
 "title": "Postgres",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAL size increase rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pg_wal_size_bytes[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "pg_wal_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WAL segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "pg_wal_segments", "legendFormat": "__auto" }
   ]
  },
  { "title": "Checkpointer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Checkpointer io",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint_total[$__rate_interval]) * 8",
     "legendFormat": "Checkpointer writes per second"
    }
   ]
  },
  {
   "title": "Checkpoints 1m delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "delta(pg_stat_bgwriter_checkpoints_req_total[1m])",
     "legendFormat": "checkpoints requested"
    },
    {
     "expr": "delta(pg_stat_bgwriter_checkpoints_timed_total[1m])",
     "legendFormat": "checkpoints timed"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "pg_stat_bgwriter_checkpoints_req_total",
     "legendFormat": "checkpoints requested"
    },
    {
     "expr": "pg_stat_bgwriter_checkpoints_timed_total",
     "legendFormat": "checkpoints schedulled"
    }
   ]
  }
 ]
}