{
 "title": "Spammer",
 "time": { "from": "2024-04-11T22:17:42.843Z", "to": "2024-04-11T22:32:21.240Z" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(runner_execution_duration_ms_count,pod)"
    }
   },
   {
    "name": "test_name",
    "label": "test_name",
    "query": {
     "query": "label_values(runner_execution_duration_ms_count,test_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Avg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg ((runner_execution_duration_ms_sum{pod=~\"$pod\", test_name=~\"$test_name\"} / runner_execution_duration_ms_count{pod=~\"$pod\", test_name=~\"$test_name\"}) > -1e12) by (pod, test_name, spammer_implementation_class)",
     "legendFormat": "{{test_name}} - {{spammer_implementation_class}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (rate (runner_execution_duration_ms_count{pod=~\"$pod\", test_name=~\"$test_name\"}[20s])) by (pod, test_name, spammer_implementation_class)",
     "legendFormat": "{{test_name}} - {{spammer_implementation_class}} - {{pod}}"
    }
   ]
  },
  {
   "title": "999 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg (histogram_quantile(0.999, runner_execution_duration_ms_bucket{pod=~\"$pod\", test_name=~\"$test_name\"}) > -1e12) by (pod, test_name, spammer_implementation_class) ",
     "legendFormat": "{{test_name}} - {{spammer_implementation_class}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Sum Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (runner_execution_duration_ms_count{pod=~\"$pod\", test_name=~\"$test_name\"}[20s])) by (pod, test_name, spammer_implementation_class)",
     "legendFormat": "{{test_name}} - {{spammer_implementation_class}} - {{pod}}"
    }
   ]
  },
  { "title": "Per runner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg ((runner_execution_duration_ms_sum{pod=~\"$pod\", test_name=~\"$test_name\"} / runner_execution_duration_ms_count{pod=~\"$pod\", test_name=~\"$test_name\"}) > -1e12) by (pod, test_name, runner_index, spammer_implementation_class)",
     "legendFormat": "{{runner_index}} - {{test_name}} - {{spammer_implementation_class}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (rate (runner_execution_duration_ms_count{pod=~\"$pod\", test_name=~\"$test_name\"}[20s])) by (pod, test_name, runner_index, spammer_implementation_class)",
     "legendFormat": "{{runner_index}} - {{test_name}} - {{spammer_implementation_class}} - {{pod}}"
    }
   ]
  },
  {
   "title": "999 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg (histogram_quantile(0.999, runner_execution_duration_ms_bucket{pod=~\"$pod\", test_name=~\"$test_name\"}) > -1e12) by (pod, test_name, runner_index, spammer_implementation_class) ",
     "legendFormat": "{{runner_index}} - {{test_name}} - {{spammer_implementation_class}} - {{pod}}"
    }
   ]
  }
 ]
}