apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Release.Name }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.1

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
        log4j.logger.kafka: "INFO"
        log4j.logger.org.apache.kafka: "INFO"
        log4j.logger.kafka.request.logger: "TRACE"
        log4j.logger.kafka.network.Processor: "INFO"
        log4j.logger.kafka.server.KafkaApis: "INFO"
        log4j.logger.kafka.network.RequestChannel$: "TRACE"

    config:
      default.replication.factor: 3
      min.insync.replicas: 2
      replica.socket.receive.buffer.bytes: -1
      socket.receive.buffer.bytes: -1
      socket.send.buffer.bytes: -1

    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

    rack:
      topologyKey: "topology.kubernetes.io/zone"

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/kafka
              operator: In
              values:
              - "true"

  entityOperator:
    topicOperator: {}
    userOperator: {}

  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"