outputPath := "../.output"
pythonPath := "./scripts/.venv/Scripts/python.exe"

ansible name args="":
    powershell.exe -c "wsl.exe -- ANSIBLE_HOST_KEY_CHECKING=False /root/.local/bin/ansible-playbook ./{{name}}/playbook.yaml -i {{outputPath}}/inventory.yaml {{args}}"

microk8s-config path:
    ssh -o StrictHostKeychecking=no ubuntu@$(cat {{outputPath}}/{{path}}/nat_ip_address.txt) -i {{outputPath}}/ssh.key "sudo kubectl config view"

microk8s-node-config-apply name:
    {{pythonPath}} ./scripts/microk8s_config_specific.py --name {{name}} --ip-path {{outputPath}}/{{name}}/nat_ip_address.txt

dns-lb-record name:
    {{pythonPath}} ./scripts/technitium_dns_record_specific.py --name {{name}}

inventory name:
    {{pythonPath}} ./scripts/build_single_node_inventory.py --name {{name}}

k3s master_name worker_names:
    {{pythonPath}} ./scripts/create_k3s_inventory.py --master-name {{master_name}} --worker-names {{worker_names}}
    just ansible k3s

apply-kubectl-config name:
    {{pythonPath}} ./scripts/apply_kubectl_config.py --name {{name}}