- name: Install packages using snap
  hosts: nodes
  become: true

  tasks:
    - name: Install sysstat
      apt:
        name: sysstat
        state: present

    - name: Install fio
      apt:
        name: fio
        state: present
    
    - name: Copy fio test
      ansible.builtin.copy:
        src: ./test.fio
        dest: /test/
    
    - name: Install perf1
      apt:
        name: linux-tools-generic
        state: present
    
    - name: Install perf2
      apt:
        name: linux-tools-common
        state: present
    
    - name: Install blktrace
      apt:
        name: blktrace
        state: present
    
    - name: Install stress
      apt:
        name: stress
        state: present

    - name: Install microk8s
      register: microk8s
      snap:
        name: microk8s
        state: present
        classic: true
      when: false
    
    - name: Enable cert-manager addon in microk8s
      command: microk8s enable cert-manager
      when: microk8s is not skipped

    - name: Enable hostpath-storage addon in microk8s
      command: microk8s enable hostpath-storage
      when: microk8s is not skipped