- name: Install packages using snap
  hosts: nodes
  become: true

  tasks:
    - name: Install sysstat
      apt:
        name: sysstat
        state: present

    - name: Install fio
      apt:
        name: fio
        state: present
    
    - name: Copy fio test
      ansible.builtin.copy:
        src: ./test.fio
        dest: /test/
    
    - name: Install fio
      apt:
        name: stress
        state: present

    - name: Install microk8s
      snap:
        name: microk8s
        state: present
        classic: true
    
    - name: Enable cert-manager addon in microk8s
      command: microk8s enable cert-manager

    - name: Enable hostpath-storage addon in microk8s
      command: microk8s enable hostpath-storage